# Generated by Django 3.2.25 on 2024-11-26 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_update', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basemodel')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=200)),
                ('vehicle_no', models.CharField(max_length=200)),
                ('running_km', models.PositiveIntegerField()),
                ('total_amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('in-progress', 'in-progress'), ('completed', 'completed')], default='in-progress', max_length=200)),
                ('service_advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('api.basemodel',),
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basemodel')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('customer_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
            bases=('api.basemodel',),
        ),
    ]
